# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-23 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20191023_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=models.TextField(max_length=400),
        ),
    ]
